apiVersion: v1
kind: Service
metadata:
  labels:
    app: rest-server
  name: rest-server-deployment
spec:
  selector:
    app: rest-server
    version: 0.0.0
  ports:
   - protocol: TCP
     port: 5000
     targetPort: 5000
  type: LoadBalancer
